/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface EsriMap {
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-WebMap.html
         */
        "esriMap": __esri.Map;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "fLayer": __esri.FeatureLayer;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html
         */
        "legend": __esri.Legend;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView": __esri.MapView;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLEsriMapElement extends Components.EsriMap, HTMLStencilElement {
    }
    var HTMLEsriMapElement: {
        prototype: HTMLEsriMapElement;
        new (): HTMLEsriMapElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "esri-map": HTMLEsriMapElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface EsriMap {
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-WebMap.html
         */
        "esriMap"?: __esri.Map;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "fLayer"?: __esri.FeatureLayer;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Legend.html
         */
        "legend"?: __esri.Legend;
        /**
          * https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView"?: __esri.MapView;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "esri-map": EsriMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "esri-map": LocalJSX.EsriMap & JSXBase.HTMLAttributes<HTMLEsriMapElement>;
        }
    }
}
